# Generated by Django 4.1.1 on 2022-09-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_comment_alter_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
